title: 100 Days of Code updates
description: Daily progress with 100 Days of Code chanllenge
author: Suela Palushi
github: https://github.com/suelap
about: I'm experimenting with Python because why not
enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/suelapalushi"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/suela-palushi-85bb4b96"
    - icon: fa-github
      link: "https://github.com/suelaP"

urls:
    - text: About Me
      url: https://suelapalushi.com

url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
